export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST'
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS'
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL'

export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST'
export const BLOG_POST_SUCCESS = 'BLOG_POST_SUCCESS'
export const BLOG_POST_FAIL = 'BLOG_POST_FAIL'

export const MY_BLOG_REQUEST = 'MY_BLOG_REQUEST'
export const MY_BLOG_SUCCESS = 'MY_BLOG_SUCCESS'
export const MY_BLOG_FAIL = 'MY_BLOG_FAIL'

export const BLOG_READ_REQUEST = 'BLOG_READ_REQUEST'
export const BLOG_READ_SUCCESS = 'BLOG_READ_SUCCESS'
export const BLOG_READ_FAIL = 'BLOG_READ__FAIL'